from enum import Enum


class TypeEntitiesEnum(str, Enum):
    DRAGON = "DRAGON"
    DRAGONNET = "DRAGONNET"
    DRAGON_MOYEN = "DRAGON_MOYEN"
    DRAGON_GEANT = "DRAGON_GEANT"
    VOLCANO = "VOLCANO"
    TORNADO = "TORNADO"
    TOWER = "TOWER"
    ISLAND_OF_LIFE = "ISLAND_OF_LIFE"
    TREASURE = "TREASURE"
    BASE = "BASE"
    EFFECT_ZONE = "EFFECT_ZONE"
    OBSTACLE = "OBSTACLE"
